# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=150, verbose_name='Başlık')),
                ('doc_content', models.TextField(max_length=1000, verbose_name='İçerik Hakkında')),
                ('publishing_date', models.DateTimeField()),
            ],
        ),
    ]
