# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
