# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-20 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191006_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosya',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='dosya',
            name='doc_image_link',
            field=models.TextField(default='#', help_text="Görselin yüklübulunduğu esas link.'Resmin adresini kopyala'", max_length=1000, verbose_name='Görselin Adresi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosya',
            name='doc_link',
            field=models.TextField(default='#', help_text='Yönlendirilecek Link', max_length=1000, verbose_name='Bağlantı Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dosya',
            name='doc_content',
            field=models.TextField(max_length=10000, verbose_name='İçerik Hakkında'),
        ),
    ]
