# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-20 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191020_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='doc_image_link',
            field=models.CharField(help_text="Görselin yüklübulunduğu esas link.'Resmin adresini kopyala'", max_length=1000, verbose_name='Görselin Adresi'),
        ),
        migrations.AlterField(
            model_name='dosya',
            name='doc_link',
            field=models.CharField(help_text='Yönlendirilecek Link', max_length=1000, verbose_name='Bağlantı Link'),
        ),
    ]
