# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-27 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191027_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosya',
            old_name='doc_tags',
            new_name='tags',
        ),
    ]
