# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-01 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191027_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='doc_image_link',
            field=models.CharField(help_text="Görselin yüklü bulunduğu esas link. 'örn:abc.com/resim.jpg | Resmin adresini kopyala'", max_length=1000, verbose_name='Görselin Adresi'),
        ),
    ]
